export const pizzaBase = [
    { value: 'thin_crust', label: 'Thin Crust' },
    { value: 'classic_crust', label: 'Classic Crust' },
    { value: 'stuffed_crust', label: 'Stuffed Crust' },
    { value: 'gluten_free', label: 'Gluten-Free' }
  ];
  
export const pizzaToppings = [
    { value: 'mozzarella', label: 'Mozzarella' },
    { value: 'basil', label: 'Basil' },
    { value: 'tomato_sauce', label: 'Tomato Sauce' },
    { value: 'pepperoni', label: 'Pepperoni' },
    { value: 'chicken', label: 'Chicken' },
    { value: 'bbq_sauce', label: 'BBQ Sauce' },
    { value: 'onions', label: 'Onions' },
    { value: 'cheddar', label: 'Cheddar' },
    { value: 'ham', label: 'Ham' },
    { value: 'pineapple', label: 'Pineapple' },
    { value: 'bell_peppers', label: 'Bell Peppers' },
    { value: 'olives', label: 'Olives' },
    { value: 'mushrooms', label: 'Mushrooms' },
    { value: 'sausage', label: 'Sausage' },
    { value: 'bacon', label: 'Bacon' },
    { value: 'buffalo_chicken', label: 'Buffalo Chicken' },
    { value: 'ranch_sauce', label: 'Ranch Sauce' },
    { value: 'blue_cheese', label: 'Blue Cheese' },
    { value: 'spinach', label: 'Spinach' },
    { value: 'alfredo_sauce', label: 'Alfredo Sauce' },
    { value: 'garlic', label: 'Garlic' },
    { value: 'parmesan', label: 'Parmesan' },
    { value: 'feta_cheese', label: 'Feta Cheese' },
    { value: 'sun_dried_tomatoes', label: 'Sun-Dried Tomatoes' },
    { value: 'ground_beef', label: 'Ground Beef' },
    { value: 'lettuce', label: 'Lettuce' },
    { value: 'steak', label: 'Steak' },
    { value: 'artichokes', label: 'Artichokes' },
    { value: 'ricotta', label: 'Ricotta' },
    { value: 'jalapenos', label: 'Jalapenos' },
    { value: 'prosciutto', label: 'Prosciutto' },
    { value: 'pesto_sauce', label: 'Pesto Sauce' },
    { value: 'eggplant', label: 'Eggplant' },
    { value: 'shrimp', label: 'Shrimp' },
    { value: 'mayonnaise', label: 'Mayonnaise' },
    { value: 'macaroni', label: 'Macaroni' },
    { value: 'truffle_oil', label: 'Truffle Oil' }
  ];